=== joaoraposooptiply/tap-vendit/archive/product.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "productId": {"type": "integer"},
    "groupId": {"type": ["integer", "null"]},
    "brandId": {"type": ["integer", "null"]},
    "brancheId": {"type": ["integer", "null"]},
    "productNumber": {"type": ["string", "null"]},
    "productType": {"type": ["string", "null"]},
    "productKindId": {"type": ["integer", "null"]},
    "productDescription": {"type": ["string", "null"]},
    "productSubdescription": {"type": ["string", "null"]},
    "additionalInfo": {"type": ["string", "null"]},
    "useStock": {"type": ["boolean", "null"]},
    "salesVisibilityId": {"type": ["integer", "null"]},
    "availabilityStatusId": {"type": ["integer", "null"]},
    "creationDatetime": {"type": ["string", "null"], "format": "date-time"},
    "productLabelLayoutId": {"type": ["integer", "null"]},
    "cabProfileCode": {"type": ["integer", "null"]},
    "allowInvoiceDiscount": {"type": ["boolean", "null"]},
    "lastModified": {"type": ["string", "null"], "format": "date-time"},
    "isModified": {"type": ["boolean", "null"]},
    "productGuid": {"type": ["string", "null"]},
    "memoCommon": {"type": ["string", "null"]},
    "memoEcommerce": {"type": ["string", "null"]},
    "isDeleted": {"type": ["boolean", "null"]},
    "productSize": {"type": ["string", "null"]},
    "modelSeason": {"type": ["string", "null"]},
    "productColor": {"type": ["string", "null"]},
    "useGroupInvoiceDiscount": {"type": ["boolean", "null"]},
    "salesUnitId": {"type": ["integer", "null"]},
    "salesUnitQuantity": {"type": ["number", "null"]},
    "hintInfo": {"type": ["string", "null"]},
    "productSearchCode": {"type": ["string", "null"]},
    "productLabelPricetagLayoutId": {"type": ["integer", "null"]},
    "productLabelPricetagActionPriceLayoutId": {"type": ["integer", "null"]},
    "isBaseProduct": {"type": ["boolean", "null"]},
    "deliveryFromWarehouse": {"type": ["integer", "null"]},
    "purchaseFromWarehouse": {"type": ["integer", "null"]},
    "viaCollectionWarehouse": {"type": ["integer", "null"]},
    "bebat": {"type": ["integer", "null"]},
    "extraCostQuantity": {"type": ["number", "null"]},
    "mintatonPosDealId": {"type": ["string", "null"]},
    "assortmentCode": {"type": ["string", "null"]},
    "modifiedBy": {"type": ["string", "null"]},
    "createdBy": {"type": ["string", "null"]},
    "originCountryCode": {"type": ["string", "null"]},
    "originCountry": {"type": ["string", "null"]},
    "suppliers": {
      "type": ["object", "null"],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "productSupplierId": {"type": ["integer", "null"]},
              "productId": {"type": ["integer", "null"]},
              "supplierId": {"type": ["integer", "null"]},
              "supplierProductNumber": {"type": ["string", "null"]},
              "preferredDefaultSupplier": {"type": ["boolean", "null"]},
              "recommendedSalesPriceInc": {"type": ["number", "null"]},
              "availabilityStatusId": {"type": ["integer", "null"]},
              "supplierStock2": {"type": ["string", "null"]},
              "lastModified": {"type": ["string", "null"], "format": "date-time"}
            }
          }
        }
      }
    },
    "salesPrices": {
      "type": ["object", "null"],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "productSalesPriceId": {"type": ["integer", "null"]},
              "productId": {"type": ["integer", "null"]},
              "salesPriceEx": {"type": ["number", "null"]},
              "recommendedSalesPriceEx": {"type": ["number", "null"]}
            }
          }
        }
      }
    },
    "productVats": {
      "type": ["object", "null"],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "productVatId": {"type": ["integer", "null"]},
              "productId": {"type": ["integer", "null"]},
              "vatId": {"type": ["integer", "null"]}
            }
          }
        }
      }
    },
    "availableStock": {
      "type": ["object", "null"],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "officeId": {"type": ["integer", "null"]},
              "productId": {"type": ["integer", "null"]},
              "sizeColorId": {"type": ["integer", "null"]},
              "availableStock": {"type": ["number", "null"]},
              "pendingProductPurchase": {"type": ["number", "null"]},
              "officeTransferOrder": {"type": ["number", "null"]},
              "officeTransferOrderIn": {"type": ["number", "null"]},
              "reserved": {"type": ["number", "null"]},
              "infoTotalCustomerOrdered": {"type": ["number", "null"]},
              "infoTotalPurchaseOrdered": {"type": ["number", "null"]},
              "productStock": {"type": ["number", "null"]}
            }
          }
        }
      }
    }
  },
  "required": ["productId"]
}

=== joaoraposooptiply/tap-vendit/products_response.json
[
  {
    "productId": 2218,
    "groupId": 1675,
    "brandId": 4,
    "brancheId": 1,
    "productNumber": "HX6042/33",
    "productType": "881604233030",
    "productKindId": 1,
    "productDescription": "For Kids HX6042/33 Standard-B\u00fcrstenk\u00f6pfe f\u00fcr Schallzahnb\u00fcrste",
    "productSubdescription": "Kids opz.borstel x2",
    "additionalInfo": "",
    "useStock": true,
    "salesVisibilityId": 1,
    "availabilityStatusId": 1,
    "creationDatetime": "2015-12-29T10:50:36.477",
    "productLabelLayoutId": 114,
    "cabProfileCode": 100004,
    "allowInvoiceDiscount": true,
    "lastModified": "2025-02-05T15:01:15.54",
    "productGuid": "8BC105B9-410A-4088-B666-B13D431C12E1",
    "memoCommon": "Kindvriendelijke reiniging    Opzetborstels ontworpen voor kleinere mondjes  De compacte For Kids-opzetborstels van de Philips Sonicare elektrische tandenborstel zijn speciaal ontworpen voor een zachte en grondige reiniging voor kinderen van alle leeftij",
    "memoEcommerce": "Philips",
    "productSize": "",
    "productColor": "blue--white",
    "useGroupInvoiceDiscount": true,
    "salesUnitQuantity": 1.0,
    "hintInfo": "",
    "productSearchCode": "HX604233",
    "isBaseProduct": true,
    "deliveryFromWarehouse": -1,
    "purchaseFromWarehouse": -1,
    "viaCollectionWarehouse": -1,
    "bebat": -1,
    "extraCostQuantity": 1,
    "mintatonPosDealId": "",
    "assortmentCode": "Z",
    "modifiedBy": "0",
    "originCountryCode": "",
    "originCountry": ""
  },
  {
    "productId": 2404,
    "groupId": 1684,
    "brandId": 4,
    "brancheId": 1,
    "productNumber": "FC6150/01",
    "productType": "883615001010",
    "productKindId": 1,
    "productDescription": "FC6150/01 MiniVac kruimelzuiger",
    "productSubdescription": "Kruimelzuiger",
    "additionalInfo": "",
    "useStock": true,
    "salesVisibilityId": 1,
    "availabilityStatusId": 2,
    "creationDatetime": "2015-12-29T10:50:56.067",
    "productLabelLayoutId": 114,
    "cabProfileCode": 100004,
    "allowInvoiceDiscount": true,
    "lastModified": "2025-02-05T15:01:00.207",
    "productGuid": "21C3C7D3-A138-4EFD-A072-891721456FE2",
    "memoCommon": "Dagelijks snel en eenvoudig schoonmaken met de Philips-kruimelzuiger. De kruimelzuiger wordt geleverd met oplaadbare batterijen en met de meegeleverde accessoires reinigt u kwetsbare oppervlakken en bereikt u de lastigste hoeken. - Optimale draadloze pres",
    "memoEcommerce": "",
    "productSize": "",
    "productColor": "white",
    "useGroupInvoiceDiscount": true,
    "salesUnitQuantity": 1.0,
    "hintInfo": "",
    "productSearchCode": "FC615001",
    "deliveryFromWarehouse": -1,
    "purchaseFromWarehouse": -1,
    "viaCollectionWarehouse": -1,
    "bebat": -1,
    "extraCostQuantity": 1,
    "mintatonPosDealId": "",
    "assortmentCode": "Z",
    "modifiedBy": "0",
    "originCountryCode": "",
    "originCountry": ""
  },
  {
    "productId": 2484,
    "groupId": 1694,
    "brandId": 4,
    "brancheId": 1,
    "productNumber": "GC9650/80",
    "productType": "889965080010",
    "productKindId": 10,
    "productDescription": "PerfectCare Elite GC9650/80 Strijkijzer met stoomgenerator",
    "productSubdescription": "",
    "additionalInfo": "",
    "useStock": true,
    "salesVisibilityId": 1,
    "availabilityStatusId": 1,
    "creationDatetime": "2015-12-29T10:51:07.553",
    "productLabelLayoutId": 114,
    "cabProfileCode": 100004,
    "allowInvoiceDiscount": true,
    "lastModified": "2025-02-05T15:01:09.163",
    "productGuid": "04B1EC8E-B39A-427C-8D98-6F3EA57BADD5",
    "memoCommon": "De stoomgenerator is uitgerust met een langere stoomslang en een langer netsnoer dan de rest van het assortiment. Hiermee kunt u gordijnen of kledingstukken verticaal eenvoudig stomen.",
    "memoEcommerce": "",
    "productSize": "0",
    "productColor": "black--purple",
    "useGroupInvoiceDiscount": true,
    "salesUnitQuantity": 1.0,
    "hintInfo": "",
    "productSearchCode": "GC965080",
    "productLabelPricetagLayoutId": 111,
    "productLabelPricetagActionPriceLayoutId": 111,
    "deliveryFromWarehouse": -1,
    "purchaseFromWarehouse": -1,
    "viaCollectionWarehouse": -1,
    "bebat": -1,
    "extraCostQuantity": 1,
    "mintatonPosDealId": "",
    "assortmentCode": "Z",
    "modifiedBy": "0",
    "originCountryCode": "",
    "originCountry": ""
  },
  {
    "productId": 2514,
    "groupId": 1730,
    "brandId": 60,
    "brancheId": 1,
    "productNumber": "SCF152/01",
    "productType": "884015201010",
    "productKindId": 1,
    "productDescription": "Niplette\u2122 SCF152/01",
    "productSubdescription": "",
    "additionalInfo": "",
    "useStock": true,
    "salesVisibilityId": 1,
    "availabilityStatusId": 2,
    "creationDatetime": "2015-12-29T10:51:11.16",
    "productLabelLayoutId": 114,
    "cabProfileCode": 100004,
    "allowInvoiceDiscount": true,
    "lastModified": "2025-02-05T15:01:07.803",
    "productGuid": "30FFE19E-74E3-46D2-AF6A-6046C0AD60D0",
    "memoCommon": "",
    "memoEcommerce": "Philips",
    "productSize": "",
    "productColor": "transparent",
    "useGroupInvoiceDiscount": true,
    "salesUnitQuantity": 1.0,
    "hintInfo": "",
    "productSearchCode": "SCF15201",
    "isBaseProduct": true,
    "deliveryFromWarehouse": -1,
    "purchaseFromWarehouse": -1,
    "viaCollectionWarehouse": -1,
    "bebat": -1,
    "extraCostQuantity": 1,
    "mintatonPosDealId": "",
    "assortmentCode": "Z",
    "modifiedBy": "0",
    "originCountryCode": "",
    "originCountry": ""
  },
  {
    "productId": 2519,
    "groupId": 1730,
    "brandId": 60,
    "brancheId": 1,
    "productNumber": "SCF167/01",
    "productType": "884016701010",
    "productKindId": 1,
    "productDescription": "Groot massagekussen, geschikt voor alle comfort-borstkolven",
    "productSubdescription": "Massagekussen",
    "additionalInfo": "",
    "useStock": true,
    "salesVisibilityId": 1,
    "availabilityStatusId": 2,
    "creationDatetime": "2015-12-29T10:51:11.687",
    "productLabelLayoutId": 185,
    "cabProfileCode": 100004,
    "allowInvoiceDiscount": true,
    "lastModified": "2025-02-05T15:01:03.363",
    "productGuid": "77FA8D30-D59A-4332-853B-79BD32B2339E",
    "memoCommon": "Dit zachte massagekussen heeft een wijdere trechter die speciaal is ontworpen voor moeders met grotere tepels. Het kussen kan worden gebruikt met de Philips AVENT Comfort-borstkolven. Bepaal met behulp van de onderstaande afbeeldingen of je de borstkolf m",
    "memoEcommerce": "",
    "productSize": "",
    "productColor": "transparent",
    "useGroupInvoiceDiscount": true,
    "salesUnitQuantity": 1.0,
    "hintInfo": "",
    "productSearchCode": "SCF16701",
    "deliveryFromWarehouse": -1,
    "purchaseFromWarehouse": -1,
    "viaCollectionWarehouse": -1,
    "bebat": -1,
    "extraCostQuantity": 1,
    "mintatonPosDealId": "",
    "assortmentCode": "Z",
    "modifiedBy": "0",
    "originCountryCode": "",
    "originCountry": ""
  },
  {
    "productId": 2764,
    "groupId": 1681,
    "brandId": 4,
    "brancheId": 1,
    "productNumber": "HF3500/01",
    "productType": "884350001010",
    "productKindId": 1,
    "productDescription": "HF3500/01 Wake-up Light",
    "productSubdescription": "Wake-up light",
    "additionalInfo": "",
    "useStock": true,
    "salesVisibilityId": 1,
    "availabilityStatusId": 1,
    "creationDatetime": "2015-12-29T10:51:40.277",
    "productLabelLayoutId": 114,
    "cabProfileCode": 100004,
    "allowInvoiceDiscount": true,
    "lastModified": "2025-02-05T15:01:03.85",
    "productGuid": "17BA3ACE-18C2-40B0-B6AD-5EEA90AB7A5C",
    "memoCommon": "Ge\u00efnspireerd door de zonsopgang maakt de Philips Wake-up Light gebruik van een unieke combinatie van licht en geluid om u op een natuurlijke manier te wekken. U wordt energieker wakker, zodat u gemakkelijk uit bed stapt. - Getest in de praktijk - Geleidel",
    "memoEcommerce": "Philips",
    "productSize": "",
    "productColor": "yellow",
    "useGroupInvoiceDiscount": true,
    "salesUnitQuantity": 1.0,
    "hintInfo": "",
    "productSearchCode": "HF350001",
    "productLabelPricetagLayoutId": 176,
    "productLabelPricetagActionPriceLayoutId": 176,
    "deliveryFromWarehouse": -1,
    "purchaseFromWarehouse": -1,
    "viaCollectionWarehouse": -1,
    "bebat": -1,
    "extraCostQuantity": 1,
    "mintatonPosDealId": "",
    "assortmentCode": "Z",
    "modifiedBy": "0",
    "originCountryCode": "",
    "originCountry": ""
  },
  {
    "productId": 2765,
    "groupId": 1681,
    "brandId": 4,
    "brancheId": 1,
    "productNumber": "HF3505/01",
    "productType": "884350501010",
    "productKindId": 1,
    "productDescription": "HF3505/01 Wake-up Light",
    "productSubdescription": "Wake-up light",
    "additionalInfo": "",
    "useStock": true,
    "salesVisibilityId": 1,
    "availabilityStatusId": 2,
    "creationDatetime": "2015-12-29T10:51:40.357",
    "productLabelLayoutId": 114,
    "cabProfileCode": 100004,
    "allowInvoiceDiscount": true,
    "lastModified": "2025-02-05T15:01:03.887",
    "productGuid": "29FE8A95-4C69-45FD-9FFF-AD61AEE9F90C",
    "memoCommon": "Word energieker wakker op natuurlijke wijze wekt Ge\u00efnspireerd door de zons opgang maakt de Philips Wake -up Light gebruik van een unieke combinatie van licht en geluid om u op een natuurlijke manier te wekken.",
    "memoEcommerce": "",
    "productSize": "",
    "productColor": "",
    "useGroupInvoiceDiscount": true,
    "salesUnitQuantity": 1.0,
    "hintInfo": "",
    "productSearchCode": "HF350501",
    "productLabelPricetagLayoutId": 184,
    "productLabelPricetagActionPriceLayoutId": 126,
    "isBaseProduct": true,
    "deliveryFromWarehouse": -1,
    "purchaseFromWarehouse": -1,
    "viaCollectionWarehouse": -1,
    "bebat": -1,
    "extraCostQuantity": 1,
    "mintatonPosDealId": "",
    "assortmentCode": "Z",
    "modifiedBy": "0",
    "originCountryCode": "",
    "originCountry": ""
  },
  {
    "productId": 10621,
